/**
 * Test Generator - Generate test templates for different frameworks
 * Used by PM SA to create tests for acceptance criteria
 */

import type { Requirement, TestCase } from "../../types/pm.ts";

/**
 * Supported test frameworks
 */
export type TestFramework = "deno" | "jest" | "vitest" | "mocha";

/**
 * Generates test templates for various frameworks
 */
export class TestGenerator {
  /**
   * Generate a test template for a requirement
   */
  generateTestTemplate(
    requirement: Requirement,
    framework: TestFramework = "deno",
  ): TestCase {
    const template = this.getTemplate(framework, requirement);

    return {
      id: `generated-${requirement.id}`,
      requirementId: requirement.id,
      type: "generated",
      template,
      status: "pending",
    };
  }

  /**
   * Get template for specific framework
   */
  private getTemplate(
    framework: TestFramework,
    requirement: Requirement,
  ): string {
    const { clarified, acceptance } = requirement;

    switch (framework) {
      case "deno":
        return this.denoTemplate(clarified, acceptance);
      case "jest":
      case "vitest":
        return this.jestTemplate(clarified, acceptance);
      case "mocha":
        return this.mochaTemplate(clarified, acceptance);
      default:
        return this.denoTemplate(clarified, acceptance);
    }
  }

  /**
   * Deno test template
   */
  private denoTemplate(description: string, acceptance: string[]): string {
    const tests = acceptance.length > 0
      ? acceptance.map((criteria) => `
  await t.step("${this.escapeString(criteria)}", async () => {
    // TODO: Implement test for: ${criteria}
    // throw new Error("Not implemented");
  });`).join("\n")
      : `
  await t.step("should meet requirements", async () => {
    // TODO: Implement test
    // throw new Error("Not implemented");
  });`;

    return `import { assertEquals, assertExists } from "https://deno.land/std/assert/mod.ts";

/**
 * Test: ${this.escapeString(description)}
 * Generated by PM SA
 */
Deno.test("${this.escapeString(description)}", async (t) => {
${tests}
});
`;
  }

  /**
   * Jest/Vitest test template
   */
  private jestTemplate(description: string, acceptance: string[]): string {
    const tests = acceptance.length > 0
      ? acceptance.map((criteria) => `
  it("${this.escapeString(criteria)}", async () => {
    // TODO: Implement test for: ${criteria}
    // expect(true).toBe(false);
  });`).join("\n")
      : `
  it("should meet requirements", async () => {
    // TODO: Implement test
    // expect(true).toBe(false);
  });`;

    return `/**
 * Test: ${this.escapeString(description)}
 * Generated by PM SA
 */
describe("${this.escapeString(description)}", () => {
${tests}
});
`;
  }

  /**
   * Mocha test template
   */
  private mochaTemplate(description: string, acceptance: string[]): string {
    const tests = acceptance.length > 0
      ? acceptance.map((criteria) => `
  it("${this.escapeString(criteria)}", async function() {
    // TODO: Implement test for: ${criteria}
    // throw new Error("Not implemented");
  });`).join("\n")
      : `
  it("should meet requirements", async function() {
    // TODO: Implement test
    // throw new Error("Not implemented");
  });`;

    return `const { expect } = require("chai");

/**
 * Test: ${this.escapeString(description)}
 * Generated by PM SA
 */
describe("${this.escapeString(description)}", function() {
${tests}
});
`;
  }

  /**
   * Escape string for use in test description
   */
  private escapeString(str: string): string {
    return str
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, " ");
  }

  /**
   * Detect which test framework a project uses
   */
  async detectFramework(cwd: string = Deno.cwd()): Promise<TestFramework> {
    // Check for deno.json
    try {
      const denoConfig = await Deno.readTextFile(`${cwd}/deno.json`);
      if (denoConfig.includes('"test"')) {
        return "deno";
      }
    } catch {
      // Not a Deno project
    }

    // Check for deno.jsonc
    try {
      await Deno.stat(`${cwd}/deno.jsonc`);
      return "deno";
    } catch {
      // No deno.jsonc
    }

    // Check package.json for Node.js test frameworks
    try {
      const pkgJson = await Deno.readTextFile(`${cwd}/package.json`);
      const pkg = JSON.parse(pkgJson);

      const deps = { ...pkg.devDependencies, ...pkg.dependencies };

      if (deps.vitest) return "vitest";
      if (deps.jest) return "jest";
      if (deps.mocha) return "mocha";
    } catch {
      // No package.json
    }

    // Default to Deno
    return "deno";
  }

  /**
   * Generate test file path based on requirement
   */
  generateTestPath(
    requirement: Requirement,
    framework: TestFramework,
    cwd: string = Deno.cwd(),
  ): string {
    const sanitized = requirement.id.replace(/[^a-zA-Z0-9-]/g, "_");

    const testDirs: Record<TestFramework, string> = {
      deno: "test",
      jest: "__tests__",
      vitest: "test",
      mocha: "test",
    };

    const extensions: Record<TestFramework, string> = {
      deno: "_test.ts",
      jest: ".test.js",
      vitest: ".test.ts",
      mocha: ".spec.js",
    };

    return `${cwd}/${testDirs[framework]}/${sanitized}${extensions[framework]}`;
  }
}

// Singleton instance for global access
export const testGenerator = new TestGenerator();
